mapping.between.countries <- data.frame(countries1 = 
                                          c("Antigua and Barbuda",
                                            "Central African Rep.",
                                            "Congo. Dem. Rep.",
                                            "Congo. Rep.",
                                            "Cote d'Ivoire" ,
                                            "Czech Rep.",
                                            "Dominican Rep.",
                                            "Hong Kong. China",
                                            "Korea. Dem. Rep.",
                                            "Korea. Rep.",
                                            "Macao. China",
                                            "Macedonia. FYR",
                                            "Micronesia. Fed. Sts." ,
                                            "Saint Vincent and the Grenadines",
                                            "Slovak Republic",
                                            "Trinidad and Tobago",
                                            "United Kingdom",
                                            "United States",
                                            "West Bank and Gaza",
                                            "Yemen. Rep." ),
                                        countries2 = c("Barbuda",
                                                       "Central African Republic",
                                                       "Congo. Dem. Rep.",
                                                       "Republic of Congo",
                                                       "Cote d'Ivoire" ,
                                                       "Czech Republic",
                                                       "Dominican Republic",
                                                       "China",
                                                       "North Korea",
                                                       "South Korea",
                                                       "Macao",
                                                       "Macedonia",
                                                       "Micronesia" ,
                                                       "Saint Vincent",
                                                       "Slovaka",
                                                       "Trinidad",
                                                       "UK",
                                                       "USA",
                                                       "West Bank and Gaza",
                                                       "Yemen" ))